server:
  port: 80

spring:
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver

  ai:
    ollama:
      chat:
        options:
          model: llama3.3
      base-url: https://772f-35-236-250-146.ngrok-free.app

logging:
  level:
    root: INFO
    com.agilesolutions.chatbot: DEBUG
    org.springframework.ai: DEBUG

twilio:
  account:
    sid: <YOUR_ACCOUNT_SID>
  auth:
    token: <YOUR_AUTH_TOKEN>
  whatsapp:
    number: whatsapp:+04<MY-SWISS-NUMBER>

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true